name: flutter_layout
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  rxdart: ^0.27.5
  flutter_hooks: ^0.18.0
  hooks_riverpod: ^2.0.2
  riverpod_annotation: ^1.0.4
  google_fonts: ^3.0.1
  go_router: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner:
  riverpod_generator: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/